CREATE TABLE CUSTOMER(
    AADHAR_NO   INT NOT NULL,
    FNAME   VARCHAR(20)   NOT NULL,
    MINIT   CHAR(2),
    LNAME   VARCHAR(20)   NOT NULL,
    PH_NO   INT NOT NULL,
    ASTATE VARCHAR(20) ,
    CITY    VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(20),
    GUEST_ID    INT NOT NULL,
    PRIMARY_KEY(GUEST_ID),
    UNIQUE(AADHAR_NO),
    ON DELETE SET NULL  ON UPDATE CASCADE,
);

CREATE TABLE RESERVATION(
    GUEST_NO    INT NOT NULL,
    RESERVATION_ID  INT NOT NULL,
    CHECKIN_DATE    DATE    NOT NULL,
    CHECKOUT_DATE   DATE    NOT NULL,
    PERIOD_STAY  INT,
    HALL_NUMBER INT,
    ROOM_NUMBER INT,
    CATEGORY    VARCHAR(20),
    PRIMARY_KEY(RESERVATION_ID),
    UNIQUE(GUEST_NO),
    CONSTRAINT RESERVING
        FOREIGN KEY(GUEST_NO)   REFERENCES  CUSTOMER(GUEST_ID),
    CONSTRAINT  RESERVING_ROOM
        FOREIGN KEY(ROOM_NUMBER)    REFERENCES  ROOM(ROOM_NUMBER),
    CONSTRAINT  RESERVING_HALL
        FOREIGN KEY(HALL_NUMBER)    REFERENCES  CONVENTION_HALL(HALL_NUMBER),
    ON  DELETE  SET NULL    ON UPDATE   CASCADE
);
CREATE TABLE ROOM(ROOM_NO INT,
CATEGORY VARCHAR(10) NOT NULL,
NO_OF_BEDS INT NOT NULL,
AIR_COND BOOLEAN NOT NULL,
CUSTOMER_ID INT,
CONSTRAINT CUSTROOM FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(GUEST_ID) ON DELETE NULL ON UPDATE CASCADE,
PRIMARY KEY ROOM_NO);

CREATE TABLE CONVENTION_HALL(HALL_NO INT,
CATEGORY VARCHAR(10) NOT NULL,
CAPACITY INT NOT NULL,
AC BOOLEAN NOT NULL,
CUST_ID INT,
CONSTRAINT CUSTHALL FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(GUEST_ID) ON DELETE NULL ON UPDATE CASCADE,
PRIMARY KEY HALL_NO);

CREATE TABLE HOUSEKEEPS(EMP_NUMBER INT,
ROOM_NUM INT,
CONSTRAINT HOUSE_EMP FOREIGN KEY(EMP_NUMBER) REFERENCES EMPLOYEE(EMP_NUMBER) ON DELETE NULL ON UPDATE CASCADE,
CONSTRAINT HOUSE_ROOM FOREIGN KEY(ROOM_NUM) REFERENCES ROOM(ROOM_NO) ON DELETE NULL ON UPDATE CASCADE);

CREATE TABLE PAYMENT(GUEST_NUM INT,
PAY_DATE DATE NOT NULL,
INVOICE_NUMBER INT NOT NULL,
PAYMENT_METHODS VARCHAR(20) NOT NULL,
CONSTRAINT PAY_GUEST FOREIGN KEY(GUEST_NUM) REFERENCES CUSTOMER(GUEST_ID) ON DELETE NULL ON UPDATE CASCADE,
CONSTRAINT PAY_INVOICE FOREIGN KEY(INVOICE_NUMBER) REFERENCES INVOICE(INVOICE_NUMBER) ON DELETE NULL ON UPDATE CASCADE);
CREATE TABLE EMPLOYEE(
    
    SALARY INT,
    FNAME VARCHAR(255) NOT NULL,
    LNAME VARCHAR(255) 
    JOIN_DATE DATE ,
    DOB DATE ,
    EMP_NUMBER INT UNIQUE, 
    PRIMARY KEY(EMP_NUMBER),
);

CREATE TABLE BILL(
    BILL_ID INT,
    AMOUNT INT NOT NULL,
    NAME VARCHAR(255),
    CONSTRAINT PERSONNAME FOREIGN KEY (NAME) REFERENCES CUSTOMER(FNAME)
        ON DELETE SET NULL  ON UPDATE CASCADE,
    DATE DATE NOT NULL,
    PH_NO INT,
    CONSTRAINT PHONENUMBERFOREIGN KEY(PH_NO) REFERENCES CUSTOMER(PHNO)
        ON DELETE SET NULL ON UPDATE CASCADE,
    PRIMARY KEY (BILL_ID),
);

CREATE TABLE INVOICE(
    INVOICE_NUMBER INT NOT NULL,
    PRIMARY KEY(INVOICE_NUMBER),
    STATUS VARCHAR(10) NOT NULL,
    INVOICE_DESCRIPTION VARCHAR(300),

);


