CREATE TABLE CUSTOMER(
    AADHAR_NO   INT NOT NULL,
    FNAME   VARCHAR(20)   NOT NULL,
    MINIT   CHAR(2),
    LNAME   VARCHAR(20)   NOT NULL,
    PH_NO   INT NOT NULL,
    ASTATE VARCHAR(20) ,
    CITY    VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(20),
    GUEST_ID    INT NOT NULL,
    PRIMARY_KEY(GUEST_ID),
    UNIQUE(AADHAR_NO),
    ON DELETE SET NULL  ON UPDATE CASCADE,
);

CREATE TABLE RESERVATION(
    GUEST_NO    INT NOT NULL,
    RESERVATION_ID  INT NOT NULL,
    CHECKIN_DATE    DATE    NOT NULL,
    CHECKOUT_DATE   DATE    NOT NULL,
    PERIOD_STAY  INT,
    HALL_NUMBER INT,
    ROOM_NUMBER INT,
    CATEGORY    VARCHAR(20),
    PRIMARY_KEY(RESERVATION_ID),
    UNIQUE(GUEST_NO),
    CONSTRAINT RESERVING
        FOREIGN KEY(GUEST_NO)   REFERENCES  CUSTOMER(GUEST_ID),
    CONSTRAINT  RESERVING_ROOM
        FOREIGN KEY(ROOM_NUMBER)    REFERENCES  ROOM(ROOM_NUMBER),
    CONSTRAINT  RESERVING_HALL
        FOREIGN KEY(HALL_NUMBER)    REFERENCES  CONVENTION_HALL(HALL_NUMBER),
    ON  DELETE  SET NULL    ON UPDATE   CASCADE
);

