CREATE TABLE CUSTOMER(
    AADHAR_NO BIGINT NOT NULL,
    FNAME   VARCHAR(20)   NOT NULL,
    MINIT   CHAR(2),
    LNAME   VARCHAR(20),
    PH_NO   BIGINT,
    ASTATE VARCHAR(20) ,
    CITY    VARCHAR(20),
    COUNTRY VARCHAR(20),
    GUEST_ID SERIAL,
    PRIMARY KEY(GUEST_ID),
    UNIQUE(AADHAR_NO)
);

CREATE TABLE RESERVATION(
    GUEST_NO    INT NOT NULL,
    RESERVATION_ID  SERIAL,
    CHECKIN_DATE    DATE    NOT NULL,
    CHECKOUT_DATE   DATE    NOT NULL,
    PERIOD_STAY  INT,
    HALL_NUMBER INT,
    ROOM_NUMBER INT,
    CATEGORY    VARCHAR(30),
    PRIMARY KEY(RESERVATION_ID),
    
    CONSTRAINT RESERVING
        FOREIGN KEY(GUEST_NO)   REFERENCES  CUSTOMER(GUEST_ID)
            ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT  RESERVING_ROOM
        FOREIGN KEY(ROOM_NUMBER)    REFERENCES  ROOM(ROOM_NO)
            ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT  RESERVING_HALL
        FOREIGN KEY(HALL_NUMBER)    REFERENCES  CONVENTION_HALL(HALL_NO)
            ON  DELETE CASCADE    ON UPDATE   CASCADE
);

CREATE TABLE ROOM(
    ROOM_NO INT NOT NULL,
    CATEGORY VARCHAR(10) NOT NULL,
    NO_OF_BEDS INT NOT NULL,
    AIR_COND BOOLEAN NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    CONSTRAINT CUSTROOM
        FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(GUEST_ID)
            ON DELETE SET NULL ON UPDATE CASCADE,
    UNIQUE(CUSTOMER_ID),
    PRIMARY KEY(ROOM_NO)
);

CREATE TABLE HOUSEKEEPS(
    EMP_NUMBER INT,
    ROOM_NUM INT,
    HALL_NUM INT
    CONSTRAINT HOUSE_EMP
        FOREIGN KEY(EMP_NUMBER) REFERENCES EMPLOYEE(EMP_NUMBER) 
            ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT HOUSE_ROOM
        FOREIGN KEY(ROOM_NUM) REFERENCES ROOM(ROOM_NO)
            ON DELETE SET NULL ON UPDATE CASCADE
    CONSTRAINT HOUSE_HALL
        FOREIGN KEY(HALL_NUM) REFERENCES CONVENTION_HALL(HALL_NO)
            ON DELETE SET NULL ON UPDATE CASCADE
);


CREATE TABLE PAYMENT(
    GUEST_NUM INT,
    PAY_DATE DATE NOT NULL,
    INVOICE_NUMBER SERIAL NOT NULL,
    PAYMENT_METHODS VARCHAR(20) NOT NULL,
    CONSTRAINT PAY_GUEST
        FOREIGN KEY(GUEST_NUM) REFERENCES CUSTOMER(GUEST_ID)
            ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT PAY_INVOICE
        FOREIGN KEY(INVOICE_NUMBER)  REFERENCES INVOICE(INVOICE_NUMBER) 
            ON DELETE SET NULL ON UPDATE CASCADE);
    
CREATE TABLE EMPLOYEE(
    SALARY INT,
    FNAME VARCHAR(25) NOT NULL,
    MINIT CHAR(2),
    LNAME VARCHAR(25), 
    JOIN_DATE DATE ,
    DOB DATE ,
    EMP_NUMBER INT, 
    PRIMARY KEY(EMP_NUMBER)
);

CREATE TABLE BILL(
    BILL_ID SERIAL,
    AMOUNT INT NOT NULL,
    NAME VARCHAR(255),
    DATE DATE NOT NULL,
    PH_NO INT,
    CUSTOMER_ID INT NOT NULL,
    PRIMARY KEY (PH_NO),
    CONSTRAINT PHONENUMBER 
        FOREIGN KEY(PH_NO) REFERENCES CUSTOMER(PH_NO)
            ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT PERSONID
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(GUEST_ID)
            ON DELETE SET NULL  ON UPDATE CASCADE
);

CREATE TABLE INVOICE(
    INVOICE_NUMBER SERIAL NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    INVOICE_DESCRIPTION VARCHAR(300),
    PRIMARY KEY(INVOICE_NUMBER)
);
CREATE TABLE CONVENTION_HALL(
    HALL_NO INT,
    CATEGORY VARCHAR(10) NOT NULL,
    CAPACITY INT NOT NULL,
    AC BOOLEAN NOT NULL,
    CUST_ID INT NOT NULL,
    CONSTRAINT CUSTHALL 
        FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(GUEST_ID) 
            ON DELETE NULL ON UPDATE CASCADE,
    PRIMARY KEY HALL_NO
);
CREATE TABLE HOTEL_MANAGER(
    START_DATE DATE,
    EMP_ID INT,
    CONSTRAINT  HMEMPLOYEE 
        FOREIGN KEY(EMP_ID) REFERENCES  EMPLOYEE(EMP_NUMBER)
            ON UPDATE   SET NULL ON DELETE SET NULL
);