    /* ROOM DETAILS OF CUSTOMER GIVEN */
    SELECT FNAME,MINIT,LNAME,GUEST_ID,AADHAR_NO,PH_NO,ASTATE,CITY,ROOM_NO,CATEGORY 
    FROM    CUSTOMER,ROOM
    WHERE GUEST_ID=CUSTOMER_ID AND CUSTOMER_ID='161';

    /* ROOM AND CUSTOMER DETAIS GIVEN A CERTAIN CATEGORY OF ROOM*/
    SELECT * FROM CUSTOMER,ROOM WHERE GUEST_ID=CUSTOMER_ID AND CATEGORY='Single room';

    /* RESRVATION AND CUSTOMER DETAILS GIVEN A CUSTOMER ID*/
    SELECT GUEST_ID,RESERVATION_ID,FNAME,LNAME,AADHAR_NO,CHECKIN_DATE,CHECKOUT_DATE,ROOM_NUMBER
    FROM    RESERVATION,ROOM,CUSTOMER
    WHERE   ROOM_NO=ROOM_NUMBER AND ROOM_NUMBER=110 AND GUEST_ID=CUSTOMER_ID AND CUSTOMER_ID=177;

    /* ROOM AND CUSTOMER DETAILS GIVEN AADHAR NO AS KEY*/
    SELECT  * FROM ROOM,CUSTOMER WHERE GUEST_ID=CUSTOMER_ID AND AADHAR_NO=304416381;

    /* ALL EMPLOYEES HOUSEKEEPING A CERTAIN ROOM*/
    SELECT * FROM EMPLOYEE AS E,HOUSEKEEPS AS H WHERE E.EMP_NUMBER=H.EMP_NUMBER AND H.HALL_NUM=1;

    /* ALL EMPLOYEES HOUSEKEEPING A CERTAIN CONVENTION HALL*/
    SELECT * FROM EMPLOYEE AS E,HOUSEKEEPS AS H WHERE E.EMP_NUMBER=H.EMP_NUMBER AND H.ROOM_NUM=110;

